import cv2
img = cv2.imread("dino2.png",-1)
cv2.imshow("originaldino",img)
cv2.waitKey(0)
greyimg = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("greyimg",greyimg)
cv2.waitKey(0)
hsvimg = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow("hsvimg",hsvimg)
cv2.waitKey(0)
print(img.shape)
r,c = img.shape[:2]
m = cv2.getRotationMatrix2D((0,0),45,1)
rotatedimg = cv2.warpAffine(img,m,(c,r))
cv2.imshow("rotatedimg",rotatedimg)
cv2.waitKey(0)
m = cv2.getRotationMatrix2D((c//2,r//2),-45,1)
rotatedimg = cv2.warpAffine(img,m,(c,r))
cv2.imshow("rotatedimg",rotatedimg)
cv2.waitKey(0)
edges=cv2.Canny(img,50,100)
cv2.imshow("edges",edges)
cv2.waitKey(0)