import cv2
img1=cv2.imread("dino2.png",cv2.IMREAD_UNCHANGED)
print(img1)
cv2.imshow("dino1",img1)
cv2.imwrite("dinoc.png",img1)
cv2.waitKey(0)
img2=cv2.imread("dino2.png",cv2.IMREAD_COLOR)
print(img2)
cv2.imshow("dino2",img2)
cv2.imwrite("dinoc2.png",img2)
cv2.waitKey(0)
img3=cv2.imread("dino2.png",cv2.IMREAD_GRAYSCALE)
print(img3)
cv2.imshow("dino3",img3)
cv2.imwrite("dinoc3.png",img3)
cv2.waitKey(0)